name: Build and Publish mod
on:
  push:
    tags:
      - "release-*.*.*"
jobs:
  build:
    outputs:
      thunderstore-package: ${{ steps.create-thunderstore-package.outputs.artifact-id }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        submodules: recursive
    - name: Set up build tools
      run: |-
        sudo apt install -y clang lld ninja-build python3
    - name: run-buildscript
      run: |-
        python3 ./create_thunderstore_package.py

    - name: read-package-info
      uses: actions/github-script@v6
      id: read-package-info
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs');
            const jsonString = fs.readFileSync('./thunderstore_package/manifest.json');
            var manifest = JSON.parse(jsonString);
            console.log(manifest)
            return manifest;
          } catch(err) {
            core.error("Error while reading or parsing the JSON");
            core.setFailed(err);
          }

    - uses: GreenTF/upload-thunderstore-package@v4.3
      with:
        namespace: LT_Schmiddy 
        token: ${{ secrets.THUNDERSTORE_TOKEN }}
        name: ${{ steps.set-result.outputs.result["name"] }} 
        description: ${{ steps.set-result.outputs.result["description"] }} 
        version: ${{ steps.set-result.outputs.result["version_number"] }} 
        community: zelda-64-recompiled
        file: ${{ steps.set-result.outputs.result.name }}.thunderstore.zip
        categories: | 
          mods
          
    - name: publish-github-release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.set-result.outputs.result.version_number }}
        body_path: ${{ github.workspace }}/thunderstore_package/CHANGELOG.md
        files: |
          ./build/*.nrm
        make_latest: true

    - name: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ThunderstorePackage
        path: |
          ./thunderstore_package/*
    
